-- Revising the Select Query I
SELECT 
* 
FROM CITY WHERE COUNTRYCODE ='USA' AND POPULATION > 100000;

-- Revising the Select Query II 
SELECT 
NAME FROM CITY
WHERE COUNTRYCODE ='USA' AND POPULATION > 120000;

-- Select All Query III
SELECT * FROM CITY;

-- Select By ID Query IV
SELECT * FROM CITY WHERE ID = 1661;

-- apanese Cities' Attributes Query v
SELECT * FROM CITY WHERE COUNTRYCODE ='JPN';

-- Japanese Cities' Names Query VI
SELECT NAME FROM CITY WHERE COUNTRYCODE ='JPN';

--  Weather Observation Station 1 Query VII
SELECT CITY, STATE FROM STATION;

--  Weather Observation Station 3 Query VIII
SELECT DISTINCT(CITY) FROM STATION WHERE ID%2 =0;

--  Weather Observation Station 4 Query IX
SELECT COUNT(CITY) - COUNT(DISTINCT(CITY)) FROM STATION; 

--  Weather Observation Station 5 Query X
SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY), CITY LIMIT 1;
SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC,CITY  LIMIT 1;

--  Weather Observation Station 6 Query XI
SELECT CITY
FROM STATION
WHERE CITY LIKE 'A%'
   OR CITY LIKE 'E%'
   OR CITY LIKE 'I%'
   OR CITY LIKE 'O%'
   OR CITY LIKE 'U%';

--  Weather Observation Station 7 Query XII
SELECT
DISTINCT(CITY)
FROM STATION
WHERE CITY LIKE '%a'
OR CITY LIKE '%e'
OR CITY LIKE '%i'
OR CITY LIKE '%o'
OR CITY LIKE '%u';

--  Weather Observation Station 8 Query XIII
SELECT DISTINCT(CITY) FROM STATION
WHERE (CITY LIKE 'A%'
OR CITY LIKE 'E%'
OR CITY LIKE 'I%'
OR CITY LIKE 'O%'
OR CITY LIKE 'U%') AND (
CITY LIKE '%a'
OR CITY LIKE '%e'
OR CITY LIKE '%i'
OR CITY LIKE '%o'
OR CITY LIKE '%u'
);

--  Weather Observation Station 9 Query XIV
SELECT DISTINCT(CITY)
FROM STATION
WHERE NOT (CITY LIKE 'A%'
   OR CITY LIKE 'E%'
   OR CITY LIKE 'I%'
   OR CITY LIKE 'O%'
   OR CITY LIKE 'U%');

--  Weather Observation Station 10 Query XV
SELECT DISTINCT(CITY)
FROM STATION
WHERE NOT (CITY LIKE '%a'
   OR CITY LIKE '%e'
   OR CITY LIKE '%i'
   OR CITY LIKE '%o'
   OR CITY LIKE '%u');

--  Weather Observation Station 11 Query XVI
SELECT DISTINCT(CITY)
FROM STATION
WHERE NOT ((CITY LIKE 'A%'
   OR CITY LIKE 'E%'
   OR CITY LIKE 'I%'
   OR CITY LIKE 'O%'
   OR CITY LIKE 'U%') AND 
(CITY LIKE '%A'
   OR CITY LIKE '%E'
   OR CITY LIKE '%I'
   OR CITY LIKE '%O'
   OR CITY LIKE '%U'));
--  Weather Observation Station 12 Query XVII
SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT LIKE 'A%'
AND CITY NOT LIKE 'E%'
AND CITY NOT LIKE 'I%'
AND CITY NOT LIKE 'O%'
AND CITY NOT LIKE 'U%'
AND CITY NOT LIKE '%a'
AND CITY NOT LIKE '%e'
AND CITY NOT LIKE '%i'
AND CITY NOT LIKE '%o'
AND CITY NOT LIKE '%u';

--  Higher Than 75 Marks Query XVIII
SELECT NAME
FROM STUDENTS
WHERE MARKS > 75
ORDER BY RIGHT(NAME, 3), ID;

-- Employees Name Query XIX
SELECT NAME FROM EMPLOYEE ORDER BY NAME;

-- Employees Salaries Query XX
SELECT NAME FROM EMPLOYEE 
WHERE SALARY > 2000 AND MONTHS < 10
ORDER BY EMPLOYEE_ID;

