-- QUERY 1 Revising Aggregations - The Count Function
SELECT COUNT(NAME) FROM CITY WHERE POPULATION > 100000;

-- QUERY 2 Revising Aggregations - The Sum Function
SELECT SUM(POPULATION) FROM CITY WHERE DISTRICT = "CALIFORNIA";

-- QUERY 3 Revising Aggregations - Averages
SELECT AVG(POPULATION) FROM CITY WHERE DISTRICT ="CALIFORNIA";

-- QUERY 4  AVERAGE POPULATION
SELECT ROUND(AVG(POPULATION),0) FROM CITY;
-- QUERY 5  TOTAL JAPAN POPULATION 
SELECT SUM(POPULATION) FROM CITY WHERE COUNTRYCODE ="JPN";

-- QUERY 6  POPULATION DENSITY DIFFERENCE
SELECT MAX(POPULATION) - MIN(POPULATION) FROM CITY;

-- QUERY 7  THE BLUNDER
SELECT CEIL(
    AVG(Salary) - AVG(REPLACE(Salary, '0', ''))
) AS error
FROM EMPLOYEES;

-- QUERY 8  TOP EARNERS
SELECT (MONTHS * SALARY) AS Total_Earnings,
COUNT(MONTHS * SALARY) AS TOTAL_COUNT FROM EMPLOYEE
GROUP BY MONTHS, SALARY
ORDER BY TOTAL_COUNT DESC LIMIT 1;

-- QUERY 9  WEATHER OBSERVATION 2
SELECT ROUND(SUM(LAT_N),2), ROUND(SUM(LONG_W),2) FROM STATION;

-- QUERY 10 WEATHER OBSERVATION 13
SELECT  ROUND(SUM(LAT_N),4) FROM STATION WHERE LAT_N BETWEEN 38.7880 AND 137.2345;

-- QUERY 11 WEATHER OBSERVATION 14
SELECT ROUND(MAX(LAT_N),4) FROM STATION WHERE LAT_N < 137.2345; 

-- QUERY 12 WEATHER OBSERVATION 15
SELECT ROUND(LONG_W,4) FROM STATION WHERE LAT_N < 137.2345
ORDER BY LAT_N DESC LIMIT 1;

-- QUERY 13  WEATHER OBSERVATION 16
SELECT ROUND(LAT_N,4) FROM STATION WHERE LAT_N > 38.7780
ORDER BY LAT_N LIMIT 1;

-- QUERY 14  WEATHER OBSERVATION 17
SELECT ROUND(LONG_W,4) FROM STATION WHERE LAT_N > 38.7780
ORDER BY LAT_N LIMIT 1;

